heistTime: 40
policePermission: "marsNapady.policja"
npc:

bank:

heistItems:
  - BLAZE_ROD 1 0 &cRozdzka_do_napadu #ITEM ILOSC DATA(DLA ZWYKLYCH ITEMOW 0) NAZWA

policeForHeist: 3
oneHeistPer: "1h"
minHeistMoney: 3000 #Liczba Calkowita!
maxHeistMoney: 6000 #Liczba Calkowita!